### ISSUE TITLE
Closing PHP tags not needed

### ISSUE THREAD

**Issue by TheDigitalOrchard** [thiagodp/phputil-flags#1]
https://github.com/thiagodp/phputil-flags/blob/d1ca4f2bcd5331d17575e6118c8c38fc1614d594/src/FlagData.php#L28

Will you accept pull requests? It's standard practice to exclude closing PHP tags when a file ends in PHP. This avoids any possibility of whitespace being sent. I'd be happy to submit a PR that removes all closing tags for you.

You can read about that in PSR-12....

https://www.php-fig.org/psr/psr-12/

**Comment by TheDigitalOrchard** [comment]
See #2 for the pull request.

**Comment by thiagodp** [comment]
Hello, @TheDigitalOrchard. Thank you. This project has its own formatting preferences and files are formatted automatically using `composer run style:fix`. It's recommended to run `composer run hooks:install` to make sure the files are formatted before submitting any changes.

Since this project is not interested in style changes, I'm closing this Issue.
